### ISSUE TITLE
initialEditorState removed in latest version

### ISSUE THREAD

**Issue by damir-i** [ozanyurtsever/verbum#16]
Is there any particular reason for removing initialEditorState from the newest version?

**Comment by ozanyurtsever** [comment]
Hello @damir-i , `initialEditorState` property of `RichTextPlugin` is deprecated with **Lexical 0.5**, see;
https://github.com/facebook/lexical/commit/8cba075fd9b135545dbfa4d8831e47284045e134

Seems like, the functionality of initializing an editor state is moved to `LexicalComposer`;
https://lexical.dev/docs/concepts/editor-state#understanding-the-editor-state

```js
<LexicalComposer initialConfig={{
  editorState: initialEditorState
}}>
  <LexicalRichTextPlugin />
  <LexicalOnChangePlugin onChange={editorState => editorStateRef.current = editorState} />
  <Button label="Save" onPress={() => {
    if (editorStateRef.current) {
      saveContent(JSON.stringify(editorStateRef.current))
    }
  }} />
</LexicalComposer>
```

We need to adapt **verbum** to this changes accordingly.

**Comment by damir-i** [comment]
Thank you for your response, I will keep using the older version until this is adapted.

**Comment by ozanyurtsever** [comment]
> Thank you for your response, I will keep using the older version until this is adapted.

[0.4.1](https://www.npmjs.com/package/verbum/v/0.4.1) is now released with `initialEditorState` feature.

**Comment by cdt-eth** [comment]
hey there @ozanyurtsever, i'm new to verbum/lexical. is `initialEditorState` how we would set an intial value in the editor?

my usecase: we have a form, onChange we save to our data, before submission a use can preview their submission (new page), but they can go back to change things, but the editor is blank. i'd like to paste back in that data we saved from their current work in progress.

so need to know how to set the ('.ContentEditable__root').innerHTML with an initial value, thanks!
