### ISSUE TITLE
Error Global CSS cannot be imported from within node_modules when using next.js

### ISSUE THREAD

**Issue by karyanayandi** [ozanyurtsever/verbum#18]
**Describe the bug**
Error Global CSS cannot be imported from within node_modules when using next.js

**Expected behavior**
I think verbum need work with next.js

**Screenshots**
![Cheese_22 12 29_19 22 49](https://user-images.githubusercontent.com/25613501/209950826-ce46853d-7a0b-452d-96ae-3ceaf12299c1.png)

**Comment by ozanyurtsever** [comment]
Hello @karyanayandi,

Check the following issue https://github.com/ozanyurtsever/verbum/issues/6
