### ISSUE TITLE
Cannot use localization

### ISSUE THREAD

**Issue by lucacox** [ozanyurtsever/verbum#19]
**Describe the bug**
setting locale to 'fr' produces this error in the console:

<img width="981" alt="image" src="https://user-images.githubusercontent.com/1597231/210223888-0686e366-0df5-4f00-b941-a2ff073043ec.png">

and no editor rendered. Unsetting locale make the editor visible, but not all the texts are translated (browser language is IT):

<img width="361" alt="image" src="https://user-images.githubusercontent.com/1597231/210224507-d7e47f6c-ddee-42e6-adce-628e6635e0a4.png">

**To Reproduce**
1. Use the example provided
2. set locale="fr"

**Expected behavior**
Editor should be localized in french

**Desktop (please complete the following information):**
 - OS: MacOS 13.0.1
 - Browser: Chrome  108.0.5359.124
 - Version: 0.4.1

**Comment by luicfrr** [comment]
This is happening without any locale too
waiting for any possible sollution

**Comment by pavel-taradajchenko** [comment]
https://github.com/ozanyurtsever/verbum/blob/4ad9cff5c6939614571e30b6670c0d8dae652725/src/EditorComposer.tsx#L9

this import is not used in compiled code, probably cause it value not used in code, so actual initialization of i18n isn't happening in npm package
