### ISSUE TITLE
react-i18next is not working?

### ISSUE THREAD

**Issue by yaruo-react-redux** [ozanyurtsever/verbum#24]
**Describe the bug**
Toolbar shows as follows.

![verbum_report01](https://user-images.githubusercontent.com/92757115/218168926-fa043999-a430-4db3-9dd4-f6007cf256a5.png)

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2
 - Browser Chrome 109.0.5414.119 (Official Build) (arm64), Firefox 109.0.1
 - Version 
   Node 18.12.1
   vite 4.0.0
   React 18.2.0

  Typescript 4.9.4

**Comment by ozanyurtsever** [comment]
I have been informed about this problem previously, it works perfectly fine when you run it in the local environment with storybook, however when it is installed and imported in an external project, it starts to be crushing.

I am very busy with my current projects, but I will try to take a look at it as soon as possible. During this time, I am open for any contributor to send a PR that can resolve this issue.

Thanks!

**Comment by ozanyurtsever** [comment]
Version 0.5.0 is now released!

https://www.npmjs.com/package/verbum/v/0.5.0
