### ISSUE TITLE
Localization not working

### ISSUE THREAD

**Issue by DiggesT** [ozanyurtsever/verbum#25]
**Describe the bug**
Editor has been crushed when `locale` prop is set (any language `'en' | 'fr' | 'ptBr'`). 

**To Reproduce**
1. Just launch the app.

**Expected behavior**
Normal behavior.

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/60646213/218245960-1979f106-8a79-48f7-8471-09b9b39a46a7.png">

**Desktop:**
 - OS: MacOS Monterey v.12.6
 - Browser: Google Chrome
 - Version: 109.0.5414.119 

**Additional info**
[Example](https://github.com/DiggesT/Verbum-locale-error).

**Comment by DiggesT** [comment]
Seems related to #24.

**Comment by ozanyurtsever** [comment]
I have been informed about this problem previously, it works perfectly fine when you run it in the local environment with storybook, however when it is installed and imported in an external project, it starts to be crushing.

I am very busy with my current projects, but I will try to take a look at it as soon as possible. During this time, I am open for any contributor to send a PR that can resolve this issue.

Thanks!

**Comment by DiggesT** [comment]
It's ok, i'll try to fix it too.

**Comment by ozanyurtsever** [comment]
Version 0.5.0 is now released!

https://www.npmjs.com/package/verbum/v/0.5.0
