### ISSUE TITLE
can't use ctrl +v paste image

### ISSUE THREAD

**Issue by m3360202** [ozanyurtsever/verbum#32]
**Describe the bug**
can't use ctrl +v paste image

**To Reproduce**
1. Go to 'editor'
2. ctrl +c copy a image
3.  ctrl +v paste to editor
4. not effect

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DiggesT** [comment]
Hello @m3360202, now it available with #48. 
I will close the issue when merged it.

You can test it in your own, use `npm install commit` for install [this](https://github.com/ozanyurtsever/verbum/pull/48/commits/e13b2c751e8bc8f5178315265f5fd4456a3dd734) commit.
