### ISSUE TITLE
Cannot start the app

### ISSUE THREAD

**Issue by trannhutle** [ozanyurtsever/verbum#4]
I am using the code like on the example page.
And that is the error message. Do you have any ideas to fix it?
Thank you.
![image](https://user-images.githubusercontent.com/14163032/175292315-30822757-58f3-4c15-ad88-28f864ce46ea.png)

**Comment by ozanyurtsever** [comment]
I have fixed it with the latest commit. f09580e2669b3aca03415db1b5721605ce4ed0ca
