### ISSUE TITLE
No way to use EditorContext nor LexicalComposerContext

### ISSUE THREAD

**Issue by DiggesT** [ozanyurtsever/verbum#7]
**Describe the bug**
I couldn't find a way to get the `editor` value.

**To Reproduce**

1. Use an example from `README`
2. Attach the following "plugin"

```typescript
const MyComponent = () => {
  const [editor] = useLexicalComposerContext();
  return <div onClick={() => console.log(editor)}>Show Editor</div>
}
```

**Expected behavior**

`editor` object should be printed

I also couldn't use `useContext(EditorContext)` because `EditorContext` doesn't seem to be exported properly.

Maybe that's an XY problem, but I was trying to get the current state of the editor to just send it via POST request and couldn't find a way to do that.

**Comment by ozanyurtsever** [comment]
Hello,

The Editor API provides an `onChange` method to access the inner state of the editor. So when you define an `Editor`, you have to give a function that will handle that for you.

```js
const NoteViewer = () => {
 const [editorState, setEditorState] = useState();

  return (
    <EditorComposer>
      <Editor onChange{(state) => setEditorState(state)}>
        <ToolbarPlugin>
          <FontFamilyDropdown />
          <FontSizeDropdown />
          <Divider />
          <BoldButton />
          <ItalicButton />
          <UnderlineButton />
          <CodeFormatButton />
          <InsertLinkButton />
          <TextColorPicker />
          <BackgroundColorPicker />
          <TextFormatDropdown />
          <Divider />
          <InsertDropdown enablePoll={true} />
          <Divider />
          <AlignDropdown />
        </ToolbarPlugin>
      </Editor>
    </EditorComposer>
  );
};
```

Every time the editor state is mutated, the function that you have provided to the `onChange` prop will be called with the value of the updated state.

Does that help?

**Comment by DiggesT** [comment]
Unfortunately no. In this case i get `JSON` structure in `editorState`.

What should i do next? How can i transform `editorState` to `Markdown`?

For example i need to use `$convertToMarkdownString()` like this:
```typescript
editorState.update(() => {
  const markdown = $convertToMarkdownString(TRANSFORMERS);
});
```

**Comment by ozanyurtsever** [comment]
> Unfortunately no. In this case i get `JSON` structure in `editorState`.
> 
> What should i do next? How can i transform `editorState` to `Markdown`?
> 
> For example i need to use `$convertToMarkdownString()` like this:
> 
> ```ts
> editorState.update(() => {
>   const markdown = $convertToMarkdownString(TRANSFORMERS);
> });
> ```

Where is the `TRANSFORMERS` coming from in this example?

As you said, you will get a stringified JSON of the editor state. If you want to deserialize a stringified state, you can use the following;

`const editorState = editor.parseEditorState(editorStateJSONString);`

Here you need an `editor` instance, however don't forget that instance is only useful for deserializing purpose here, otherwise it does not connected with the editor that is initialized when you use this package, because the main editor has a separate, inner context by itself.

**Comment by DiggesT** [comment]
`TRANSFORMERS` imported via `import { TRANSFORMERS } from '@lexical/markdown'`.

> Here you need an editor instance

Yup, sorry that was probably poorly phrased question, but that's what I needed initially, an `editor` instance.

**Comment by ozanyurtsever** [comment]
In that case, can you open a feature request as an issue for that?

**Comment by ozanyurtsever** [comment]
Moved to #8
